apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - xpanse-service-account.yaml
  - xpanse-config-map.yaml
  - xpanse.yaml
  - ui.yaml
  - policy-man.yaml
  - terra-boot.yaml
  - tofu-maker.yaml
