apiVersion: v1
kind: ConfigMap
metadata:
  name: terra-boot-config
data:
  LOG_TERRAFORM_STDOUT_STDERR: "true"
  TERRAFORM_ROOT_MODULE_DIRECTORY: "/tmp/terra-boot"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terra-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terra-boot
  template:
    metadata:
      labels:
        app: terra-boot
    spec:
      containers:
        - name: terra-boot
          image: ghcr.io/eclipse-xpanse/terra-boot:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: terra-boot-config
          ports:
            - containerPort: 9090
          readinessProbe:
            httpGet:
              port: 9090
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 9090
              path: /actuator/health/liveness

---
apiVersion: v1
kind: Service
metadata:
  name: terra-boot-service
spec:
  selector:
    app: terra-boot
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  clusterIP: None # ClusterIP type (default, but specifying it for clarity)

