apiVersion: v1
kind: ConfigMap
metadata:
  name: terra-boot-config
data:
  LOG_TERRAFORM_STDOUT_STDERR: "true"
  TERRAFORM_ROOT_MODULE_DIRECTORY: "/tmp/terra-boot"
  SPRING_PROFILES_ACTIVE: "dev,opentelemetry"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terra-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terra-boot
  template:
    metadata:
      labels:
        app: terra-boot
    spec:
      containers:
        - name: terra-boot
          image: ghcr.io/eclipse-xpanse/terra-boot:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: terra-boot-config
          ports:
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: terra-boot-service
spec:
  selector:
    app: terra-boot
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  clusterIP: None # ClusterIP type (default, but specifying it for clarity)

