---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tofu-maker-config
data:
  LOG_TERRAFORM_STDOUT_STDERR: "true"
  TERRAFORM_ROOT_MODULE_DIRECTORY: "/tmp/tofu-maker"
  SPRING_PROFILES_ACTIVE: "dev,opentelemetry"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tofu-maker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tofu-maker
  template:
    metadata:
      labels:
        app: tofu-maker
    spec:
      containers:
        - name: tofu-maker
          image: ghcr.io/eclipse-xpanse/tofu-maker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: tofu-maker-config
          ports:
            - containerPort: 9092
          readinessProbe:
            httpGet:
              port: 9092
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 9092
              path: /actuator/health/liveness
---
apiVersion: v1
kind: Service
metadata:
  name: tofu-maker-service
spec:
  selector:
    app: tofu-maker
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  clusterIP: None
