---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-config-sa
  namespace: xpanse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-config-role
  namespace: xpanse
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-config-rolebinding
  namespace: xpanse
subjects:
  - kind: ServiceAccount
    name: spring-config-sa
    namespace: xpanse
roleRef:
  kind: Role
  name: spring-config-role
  apiGroup: rbac.authorization.k8s.io
