---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - ../../base/core/
 - loadbalancer.yaml

patches:
  - path: patch-dev.yaml

namespace: xpanse

configMapGenerator:
 - name: tofu-maker-config
   behavior: merge
   literals:
     - SPRING_PROFILES_ACTIVE="dev"
 - name: terra-boot-config
   behavior: merge
   literals:
     - SPRING_PROFILES_ACTIVE="dev"
     - OTEL_EXPORTER_OTLP_ENDPOINT="http://otel-collector-service:4318"